# Generated by Django 6.0.4 on 2026-04-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintoken',
            name='mc_name',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MinecraftProfile',
        ),
    ]
